// <auto-generated />
using System;
using Bevent.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210072507_AddAdminEventHalls")]
    partial class AddAdminEventHalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bevent.Api.Domain.AvailableSchedules.AvailableSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("EventHallId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_hall_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_available_schedules");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_available_schedules_created_on_utc");

                    b.HasIndex("DayOfWeek")
                        .HasDatabaseName("ix_available_schedules_day_of_week");

                    b.HasIndex("EventHallId")
                        .HasDatabaseName("ix_available_schedules_event_hall_id");

                    b.HasIndex("EventHallId", "DayOfWeek")
                        .HasDatabaseName("ix_available_schedules_event_hall_id_day_of_week");

                    b.ToTable("available_schedules", "public");
                });

            modelBuilder.Entity("Bevent.Api.Domain.EventHallImages.EventHallImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventHallId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_hall_id");

                    b.Property<string>("ImagePublicId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_public_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_event_hall_images");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_event_hall_images_created_on_utc");

                    b.HasIndex("EventHallId")
                        .HasDatabaseName("ix_event_hall_images_event_hall_id");

                    b.HasIndex("ImagePublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_hall_images_image_public_id");

                    b.ToTable("event_hall_images", "public");
                });

            modelBuilder.Entity("Bevent.Api.Domain.EventHalls.EventHall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_event_halls");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_event_halls_admin_id");

                    b.HasIndex("BasePrice")
                        .HasDatabaseName("ix_event_halls_base_price");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_event_halls_created_on_utc");

                    b.HasIndex("MaxCapacity")
                        .HasDatabaseName("ix_event_halls_max_capacity");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_event_halls_name");

                    b.ToTable("event_halls", "public");
                });

            modelBuilder.Entity("Bevent.Api.Domain.ReservationServices.ReservationService", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("PriceAtReservation")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_at_reservation");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("ReservationId", "ServiceId")
                        .HasName("pk_reservation_services");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_reservation_services_created_on_utc");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_reservation_services_service_id");

                    b.ToTable("reservation_services", "public");
                });

            modelBuilder.Entity("Bevent.Api.Domain.ReservationTasks.ReservationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_reservation_tasks");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_reservation_tasks_created_on_utc");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("ix_reservation_tasks_is_completed");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_reservation_tasks_reservation_id");

                    b.ToTable("reservation_tasks", "public");
                });

            modelBuilder.Entity("Bevent.Api.Domain.Reservations.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("EventHallId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_hall_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_cost");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_reservations_client_id");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_reservations_created_on_utc");

                    b.HasIndex("EventHallId")
                        .HasDatabaseName("ix_reservations_event_hall_id");

                    b.HasIndex("ReservationDate")
                        .HasDatabaseName("ix_reservations_reservation_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reservations_status");

                    b.HasIndex("EventHallId", "ReservationDate")
                        .HasDatabaseName("ix_reservations_event_hall_id_reservation_date");

                    b.ToTable("reservations", "public");
                });

            modelBuilder.Entity("Bevent.Api.Domain.Services.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdditionalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("additional_cost");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventHallId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_hall_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_services_created_on_utc");

                    b.HasIndex("EventHallId")
                        .HasDatabaseName("ix_services_event_hall_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_services_name");

                    b.ToTable("services", "public");
                });

            modelBuilder.Entity("Bevent.Api.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClerkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clerk_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ClerkId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_clerk_id");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_users_created_on_utc");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Bevent.Api.Domain.AvailableSchedules.AvailableSchedule", b =>
                {
                    b.HasOne("Bevent.Api.Domain.EventHalls.EventHall", "EventHall")
                        .WithMany("AvailableSchedules")
                        .HasForeignKey("EventHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_available_schedules_event_halls_event_hall_id");

                    b.Navigation("EventHall");
                });

            modelBuilder.Entity("Bevent.Api.Domain.EventHallImages.EventHallImage", b =>
                {
                    b.HasOne("Bevent.Api.Domain.EventHalls.EventHall", "EventHall")
                        .WithMany("EventHallImages")
                        .HasForeignKey("EventHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_hall_images_event_halls_event_hall_id");

                    b.Navigation("EventHall");
                });

            modelBuilder.Entity("Bevent.Api.Domain.EventHalls.EventHall", b =>
                {
                    b.HasOne("Bevent.Api.Domain.Users.User", "Admin")
                        .WithMany("EventHalls")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_halls_users_admin_id");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Bevent.Api.Domain.ReservationServices.ReservationService", b =>
                {
                    b.HasOne("Bevent.Api.Domain.Reservations.Reservation", "Reservation")
                        .WithMany("ReservationServices")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_services_reservations_reservation_id");

                    b.HasOne("Bevent.Api.Domain.Services.Service", "Service")
                        .WithMany("ReservationServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_services_services_service_id");

                    b.Navigation("Reservation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Bevent.Api.Domain.ReservationTasks.ReservationTask", b =>
                {
                    b.HasOne("Bevent.Api.Domain.Reservations.Reservation", "Reservation")
                        .WithMany("ReservationTasks")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_tasks_reservations_reservation_id");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Bevent.Api.Domain.Reservations.Reservation", b =>
                {
                    b.HasOne("Bevent.Api.Domain.Users.User", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_users_client_id");

                    b.HasOne("Bevent.Api.Domain.EventHalls.EventHall", "EventHall")
                        .WithMany("Reservations")
                        .HasForeignKey("EventHallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_event_halls_event_hall_id");

                    b.Navigation("Client");

                    b.Navigation("EventHall");
                });

            modelBuilder.Entity("Bevent.Api.Domain.Services.Service", b =>
                {
                    b.HasOne("Bevent.Api.Domain.EventHalls.EventHall", "EventHall")
                        .WithMany("Services")
                        .HasForeignKey("EventHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_services_event_halls_event_hall_id");

                    b.Navigation("EventHall");
                });

            modelBuilder.Entity("Bevent.Api.Domain.EventHalls.EventHall", b =>
                {
                    b.Navigation("AvailableSchedules");

                    b.Navigation("EventHallImages");

                    b.Navigation("Reservations");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Bevent.Api.Domain.Reservations.Reservation", b =>
                {
                    b.Navigation("ReservationServices");

                    b.Navigation("ReservationTasks");
                });

            modelBuilder.Entity("Bevent.Api.Domain.Services.Service", b =>
                {
                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("Bevent.Api.Domain.Users.User", b =>
                {
                    b.Navigation("EventHalls");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
